sonar.projectKey=Josmaryppirelag17_portfolio-v2
sonar.projectName=portfolio-v2
sonar.organization=josmaryppirelag17

sonar.sources=src/
sonar.tests=tests/

sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/playwright-report/**,\
  **/test-results/**,\
  **/coverage/**,\
  **/dist/**,\
  **/build/**,\
  src/types/**

sonar.cpd.exclusions=\
  **/tests/**/*,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/__tests__/**/*

sonar.test.inclusions=\
  **/tests/**/*.test.ts,\
  **/tests/**/*.test.tsx,\
  **/__tests__/**/*

sonar.coverage.exclusions=\
  **/tests/**/*,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/playwright-report/**/*,\
  **/test-results/**/*,\
  src/middleware.ts,\
  src/app/**,\
  src/lib/db/migrations/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.javascript.maxFileSize=2000
