sonar.projectKey=Josmaryppirelag17_portfolio-next
sonar.projectName=portfolio-next
sonar.organization=josmaryppirelag17

sonar.sources=src/

sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/playwright-report/**,\
  **/test-results/**,\
  **/coverage/**,\
  **/dist/**,\
  **/build/**,\
  **/tests/**,\
  src/types/**

sonar.coverage.exclusions=\
  **/tests/**/*,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/playwright-report/**/*,\
  **/test-results/**/*,\
  src/middleware.ts,\
  src/app/**,\
  src/lib/db/migrations/**,\
  src/workers/**,\
  src/app/opengraph-image.tsx,\
  src/i18n/**,\
  src/types/**,\
  src/lib/analytics.ts,\
  src/components/organisms/HeroPlayground.tsx,\
  src/components/organisms/AdminConsole.tsx,\
  src/components/organisms/ContactTerminal.tsx,\
  src/components/organisms/CyberAvatar.tsx,\
  src/components/organisms/SoundEngine.ts,\
  src/components/molecules/WidgetBiorhythmECG.tsx,\
  src/components/molecules/WidgetMatrixRain.tsx,\
  src/components/molecules/MatrixRainOverlay.tsx,\
  src/hooks/useCanvas.ts,\
  src/hooks/useWorker.ts,\
  src/components/templates/App.tsx

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.javascript.maxFileSize=2000
